### ISSUE TITLE
Hello! No such file or directory: './datasets/coco/train_support_df.pkl' Would you like to tell how to get the train_support_df.pkl

### ISSUE THREAD

**Issue by MrCrightH** [GuangxingHan/Meta-Faster-R-CNN#12]
Traceback (most recent call last):
  File "fsod_train_net.py", line 211, in <module>
    args=(args,),
  File "/home/ch/anaconda3/envs/ch/lib/python3.7/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "fsod_train_net.py", line 197, in main
    trainer = Trainer(cfg)
  File "/home/ch/anaconda3/envs/ch/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 378, in __init__
    data_loader = self.build_train_loader(cfg)
  File "fsod_train_net.py", line 55, in build_train_loader
    mapper = DatasetMapperWithSupportCOCO(cfg)
  File "/home/ch/Meta-Faster-R-CNN/meta_faster_rcnn/data/dataset_mapper_coco.py", line 99, in __init__
    self.support_df = pd.read_pickle("./datasets/coco/train_support_df.pkl")
  File "/home/ch/anaconda3/envs/ch/lib/python3.7/site-packages/pandas/io/pickle.py", line 169, in read_pickle
    f, fh = get_handle(fp_or_buf, "rb", compression=compression, is_text=False)
  File "/home/ch/anaconda3/envs/ch/lib/python3.7/site-packages/pandas/io/common.py", line 499, in get_handle
    f = open(path_or_buf, mode)
FileNotFoundError: [Errno 2] No such file or directory: './datasets/coco/train_support_df.pkl'

**Comment by GuangxingHan** [comment]
You need first to run the scripts of data preparation here https://github.com/GuangxingHan/Meta-Faster-R-CNN#data-preparation
