### ISSUE TITLE
ValueError: a must be greater than 0 unless no samples are taken

### ISSUE THREAD

**Issue by glory21** [GuangxingHan/Meta-Faster-R-CNN#14]
when I train my dataset, there is an error:

File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/detectron2/data/common.py", line 41, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/data/dataset_mapper_pascal_voc.py", line 129, in __call__
    support_images, support_bboxes, support_cls = self.generate_support(dataset_dict)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/data/dataset_mapper_pascal_voc.py", line 267, in generate_support
    other_cls = self.support_df.loc[(~self.support_df['category_id'].isin(used_category_id)), 'category_id'].drop_duplicates().sample().tolist()[0]
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/pandas/core/generic.py", line 5365, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 909, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

help please

**Comment by GuangxingHan** [comment]
Thanks for pointing out this issue. It is an interesting problem.
This error indicates that we could not find enough number of classes which does not appear in this image as negative class. In this case, we should not use this image for meta-training. 
One way to avoid this problem is to split this image into several parts so that there are smaller number of classes in each parts compared using the whole image.

**Comment by glory21** [comment]
Thanks for you reply! I have changed my dataset. However, there is a new error:

  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/modeling/fsod/fsod_rcnn.py", line 207, in forward
    pos_pred_class_logits, pos_pred_proposal_deltas, pos_detector_proposals = self.roi_heads(query_images, query_features, pos_support_box_features, pos_proposals, query_gt_instances) # pos rcnn
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/modeling/fsod/fsod_roi_heads.py", line 139, in forward
    pred_class_logits, pred_proposal_deltas = self.box_predictor(box_features, support_box_features)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/modeling/fsod/fsod_fast_rcnn.py", line 583, in forward
    out_fc = F.relu(self.fc_1(cat_fc), inplace=True)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

Help please!

**Comment by glory21** [comment]
> Thanks for pointing out this issue. It is an interesting problem. This error indicates that we could not find enough number of classes which does not appear in this image as negative class. In this case, we should not use this image for meta-training. One way to avoid this problem is to split this image into several parts so that there are smaller number of classes in each part compared using the whole image.

Thanks for you reply! I have changed my dataset. However, there is a new error:

 File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/modeling/fsod/fsod_rcnn.py", line 207, in forward
    pos_pred_class_logits, pos_pred_proposal_deltas, pos_detector_proposals = self.roi_heads(query_images, query_features, pos_support_box_features, pos_proposals, query_gt_instances) # pos rcnn
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/modeling/fsod/fsod_roi_heads.py", line 139, in forward
    pred_class_logits, pred_proposal_deltas = self.box_predictor(box_features, support_box_features)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/modeling/fsod/fsod_fast_rcnn.py", line 583, in forward
    out_fc = F.relu(self.fc_1(cat_fc), inplace=True)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

Help please!

**Comment by GuangxingHan** [comment]
Can you clarify which stage are you in? Is this during meta-learning or fine-tuning? If meta-learning, which step are you in?

**Comment by glory21** [comment]
> Thanks for the feedback. Can you clarify which stage are you in? Is this during meta-learning or fine-tuning? If it is meta-learning, which step are you in?

Thanks for your reply. This is during meta-learning. The Error is as follows：

/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/detectron2/layers/wrappers.py:226: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  return x.nonzero().unbind(1)
/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/detectron2/layers/wrappers.py:226: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  return x.nonzero().unbind(1)
Traceback (most recent call last):
  File "fsod_train_net.py", line 216, in <module>
    args=(args,),
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/fsod_train_net.py", line 203, in main
    return trainer.train()
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 399, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 140, in train
    self.run_step()
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 226, in run_step
    loss_dict = self.model(data)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/modeling/fsod/fsod_rcnn.py", line 207, in forward
    pos_pred_class_logits, pos_pred_proposal_deltas, pos_detector_proposals = self.roi_heads(query_images, query_features, pos_support_box_features, pos_proposals, query_gt_instances) # pos rcnn
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/modeling/fsod/fsod_roi_heads.py", line 139, in forward
    pred_class_logits, pred_proposal_deltas = self.box_predictor(box_features, support_box_features)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/kunyan/Meta-Faster-R-CNN-main/meta_faster_rcnn/modeling/fsod/fsod_fast_rcnn.py", line 583, in forward
    out_fc = F.relu(self.fc_1(cat_fc), inplace=True)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/whb/anaconda3/envs/meta-frcnn1/lib/python3.7/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by GuangxingHan** [comment]
It seems that the error is because the dimension of the concatenated feature 'cat_fc' does not match with the fully-connected layer self.fc_1. Can you debug the program yourself what happened there?
