### ISSUE TITLE
Dear author, I would like to ask what may cause the following problems in the process of generating support sets when running your code:

### ISSUE THREAD

**Issue by yinchuchen** [GuangxingHan/Meta-Faster-R-CNN#20]
Dear author, I would like to ask what may cause the following problems in the process of generating support sets when running your code:

python datasets/coco/2_gen_support_pool.py
[u'info', u'licenses', u'images', u'annotations', u'categories']
loading annotations into memory...
Done (t=5.84s)
creating index...
index created!
0
('path:', '/home/lthpc/Annotation/CH/Meta-Faster-R-CNN-main/datasets/coco/support/trainval2014/COCO_train2014_000000262146.jpg')
/home/lthpc/Annotation/CH/Meta-Faster-R-CNN-main/datasets/coco/support/trainval2014/COCO_train2014_000000262146.jpg
('img.shape', None)
Traceback (most recent call last):
  File "datasets/coco/2_gen_support_pool.py", line 267, in <module>
    support_df = main()
  File "datasets/coco/2_gen_support_pool.py", line 243, in main
    support_img, support_box = crop_support(im, bbox)
  File "datasets/coco/2_gen_support_pool.py", line 51, in crop_support
    image_shape = img.shape[:2]# h, w
**AttributeError: 'NoneType' object has no attribute 'shape'**

**Comment by yinchuchen** [comment]
Hello, I checked that the picture exists in/coco/train2014/, and whether s/coco/support/trainval2014/is created by 2_ gen_ support_ pool. Whether there is a problem in the generation process, or whether there are any files that need to be downloaded

**Comment by yinchuchen** [comment]
Hello, I checked that the picture exists in ./coco/train2014/, and whether ./coco/support/trainval2014/is created by 2_ gen_ support_ pool. Whether there is a problem in the generation process, or whether there are any files that need to be downloaded

**Comment by GuangxingHan** [comment]
1. Yes, coco/support/trainval2014 is created by the script.
2. As far as I know, lots of people have used this projects so far, and I did not know any problem yet.
3. We prepare the dataset following TFA (https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/README.md#coco). One thing to keep in mind is to copy the original val images to the train folder. But as you can find the images with the printed path, it should not be a problem.

Can you debug the python script yourself? Although I am not clear about the exact problem, I think it may not be a big issue.
