### ISSUE TITLE
 I want to run my own dataset on your work.

### ISSUE THREAD

**Issue by DaDogs** [GuangxingHan/Meta-Faster-R-CNN#24]
Hello, thank you very much for your work, but I have a question. I want to run my own dataset on your work. It is in voc format. How can I run it?Can you give me an operation manual?

**Comment by GuangxingHan** [comment]
You can follow the instructions [here](https://github.com/GuangxingHan/Meta-Faster-R-CNN#data-preparation) to prepare the training dataset. Then, you can follow the instructions [here](https://github.com/GuangxingHan/Meta-Faster-R-CNN#model-training-and-evaluation-on-pascal-voc) to train the models.

**Comment by DaDogs** [comment]
你会中文吗，我仅仅将 Meta-Faster-R-CNN-main/datasets/pascal_voc/builtin_meta_pascal_voc.py文件中的这个部分修改为
`PASCAL_VOC_ALL_CATEGORIES = {
    1: ['Hole', 'Fold', 'Black', 'Crake'],
    2: ['Hole', 'Fold', 'Black', 'Crake'],
    3: ['Hole', 'Fold', 'Black', 'Crake'],
}

PASCAL_VOC_NOVEL_CATEGORIES = {
    1: ['Hole', 'Black'],
    2: ['Hole', 'Black'],
    3: ['Hole', 'Black'],
}

# Fold  Crake
PASCAL_VOC_BASE_CATEGORIES = {
    1: ['Fold', 'Crake'],
    2: ['Fold', 'Crake'],
    3: ['Fold', 'Crake'],
}`

然后，我运行了2_gen_support_pool.py，但是他报错，我是不是还有其他的地方没修改。

python 2_gen_support_pool.py 

Traceback (most recent call last):
  File "2_gen_support_pool.py", line 261, in <module>
    root_path = sys.argv[1]
IndexError: list index out of range

**Comment by GuangxingHan** [comment]
You can add the root_path in the command like "python 2_gen_support_pool.py [root_path]"

**Comment by Fyzde** [comment]
> 你会中文吗，我仅仅将 Meta-Faster-R-CNN-main/datasets/pascal_voc/builtin_meta_pascal_voc.py文件中的这个部分修改为 `PASCAL_VOC_ALL_CATEGORIES = { 1: ['Hole', 'Fold', 'Black', 'Crake'], 2: ['Hole', 'Fold', 'Black', 'Crake'], 3: ['Hole', 'Fold', 'Black', 'Crake'], }
> 
> PASCAL_VOC_NOVEL_CATEGORIES = { 1: ['Hole', 'Black'], 2: ['Hole', 'Black'], 3: ['Hole', 'Black'], } PASCAL_VOC_BASE_CATEGORIES = { 1: ['Fold', 'Crake'], 2: ['Fold', 'Crake'], 3: ['Fold', 'Crake'], }`
> 
> 然后，我运行了2_gen_support_pool.py，但是他报错，我是不是还有其他的地方没修改。
> 
> python 2_gen_support_pool.py
> 
> Traceback (most recent call last): File "2_gen_support_pool.py", line 261, in root_path = sys.argv[1] IndexError: list index out of range

请问这个问题你解决了吗？
